### ISSUE TITLE
Create a Page Header

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/unpoll#12]
The page header should take two lines of text and look like this:

![image](https://user-images.githubusercontent.com/3317487/111385741-7904a380-8668-11eb-96f4-852e03352165.png)

input:
majorLine
minorLine

https://www.figma.com/file/qHaWXR2BKhyz34N95tThgB/Unpoll-Design?node-id=1%3A293

**Comment by ddfridley** [comment]
@nancyheiss Can you name the component PageHeader rather than just Header.  header is a really generic term I'v seen too many times.

**Comment by nancyheiss** [comment]
@ddfridley sure thing!
