### ISSUE TITLE
Card List Grouper

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/unpoll#15]
In this view: https://www.figma.com/proto/sd8Sfv0mEbmwMrumbpjcPs/Unpoll?node-id=905%3A13059&scaling=scale-down&page-id=900%3A12241

- [ ] A list of TopicCards or CardStacks should be shown. 
- [ ] At the bottom is a control button.
- [ ] If you click on a card, it turns into a CardStack ( see app/components/card-stack) and moves to the top of the list by smoothly scrolling upward.
- [ ] If you click on another card, it is removed from the list and added to the card stack.
- [ ] The departure from the list should be an animated vertical shrinking of the card.
- [ ] The control button at the bottom should say "no topics to combine, skip" when no CardStack is being created.
- [ ] If a CardStack is being created, the control button should be gray, inactive, and say "Complete Group to Continue"
**Stretch goal**:
- [ ] The browser's back, and forward buttons move you back ward and forward in history.  And Redux is not acceptable (long talk if requested)

consider, react-flip-move or react-flip-toolkit for animation of list, but open to other things too

# Inputs
```
cardObjs: [
  {id: "abc123", description: "this is a topic"},
  [
    {id: "abc234", description: "this is a topic in a group"},
    {id: "abc345", description: "this is another topic in the group"}
  ]
 ]
onComplete: ()=>{function to be called when grouping is complete}
```
The component will mutate cardObjs as the users groups cards

![image](https://user-images.githubusercontent.com/3317487/124958369-f0bb5d00-dfce-11eb-8626-0f3c36140828.png)

**Comment by ddfridley** [comment]
@BolunThompson How is it going with this?  I need to fix some React Warnings in card-list-selector but I don't want to interfere with what you are doing.  thx

**Comment by BolunThompson** [comment]
You can fix them, I haven't made much progress yet because I've been busy.

**Comment by ddfridley** [comment]
#32
